export default {
    products: [{
        _id: '1',
        name: 'Seriously Strechy Medium Wash',
        category: 'Jackets',
        image: '/images/product-1.png',
        price: 30,
        brand: "Denim",
        rating: 4.5,
        numReviews: 40,
        countInStock: 16,
    }, {
        _id: '2',
        name: "Men's 501 Wrangler Tucker",
        category: 'Jackets',
        image: '/images/product-2.png',
        price: 45,
        brand: 'Wrangler',
        rating: 4.5,
        numReviews: 10,
        countInStock: 26,
    }, {
        _id: '3',
        name: "Men's Check Blazer Custom",
        category: 'Jackets',
        image: '/images/product-3.png',
        price: 25,
        brand: "Black Lapel",
        rating: 3.0,
        numReviews: 150,
        countInStock: 36,
    }, {
        _id: '4',
        name: "Manchester Guy's Regular Wear",
        category: 'Jackets',
        image: '/images/product-4.png',
        price: 25,
        brand: "Levi's",
        rating: 4.0,
        numReviews: 10,
        countInStock: 65,
    }, {
        _id: '5',
        name: "KMTREM Women's Leather Jacket",
        category: 'Jackets',
        image: '/images/product-5.png',
        price: 60,
        brand: "KMTREM",
        rating: 4.0,
        numReviews: 540,
        countInStock: 106,
    }, {
        _id: '6',
        name: "Minneapolis Women's Classic Jean",
        category: 'Jackets',
        image: '/images/product-6.png',
        price: 40,
        brand: "Levi's",
        rating: 4.5,
        numReviews: 140,
        countInStock: 6,
    }, {
        _id: '7',
        name: "Cool Dude's Furry Jacket",
        category: 'Jackets',
        image: '/images/product-7.png',
        price: 50,
        brand: "Levi's",
        rating: 4.5,
        numReviews: 9480,
        countInStock: 106,
    }, {
        _id: '8',
        name: "Experience- Mature Man's Choice",
        category: 'Jackets',
        image: '/images/product-8.png',
        price: 40,
        brand: "Benettons",
        rating: 4.5,
        numReviews: 90,
        countInStock: 206,
    }, {
        _id: '9',
        name: "All About Leather",
        category: 'Jackets',
        image: '/images/product-9.png',
        price: 50,
        brand: "Levi's",
        rating: 3.0,
        numReviews: 1910,
        countInStock: 46,
    }, {
        _id: '10',
        name: "Women's Stylish Leather Jacket",
        category: 'Jackets',
        image: '/images/product-10.png',
        price: 30,
        brand: "Ann Taylor",
        rating: 4.5,
        numReviews: 100,
        countInStock: 26,
    }, {
        _id: '11',
        name: "Light Spring Casual",
        category: 'Jackets',
        image: '/images/product-11.png',
        price: 20,
        brand: "California",
        rating: 4.5,
        numReviews: 10,
        countInStock: 13,
    }, {
        _id: '12',
        name: "Sleeveless Winter Down Jacket",
        category: 'Jackets',
        image: '/images/product-12.png',
        price: 30,
        brand: "Northface",
        rating: 4.5,
        numReviews: 946,
        countInStock: 6,
    }, ],
};