export default {
    products: [{
        _id: '1',
        name: 'Seriously Strechy Medium Wash',
        category: 'Jackets',
        image: '/images/product-1.png',
        price: 30,
        brand: "Denim",
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    }, {
        _id: '2',
        name: "Men's 501 Wrangler Tucker",
        category: 'Jackets',
        image: '/images/product-2.png',
        price: 45,
        brand: 'Wrangler',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    }, {
        _id: '3',
        name: "Men's Check Blazer Custom",
        category: 'Jackets',
        image: '/images/product-3.png',
        price: 45,
        brand: "Black Lapel",
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    }, {
        _id: '4',
        name: "Manchester Guy's Regular Wear",
        category: 'Jackets',
        image: '/images/product-4.png',
        price: 25,
        brand: "Levi's",
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    }, {
        _id: '5',
        name: "KMTREM Women's Leather Jacket",
        category: 'Jackets',
        image: '/images/product-5.png',
        price: 60,
        brand: "KMTREM",
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    }, {
        _id: '6',
        name: "Minneapolis Women's Classic Jean",
        category: 'Jackets',
        image: '/images/product-6.png',
        price: 40,
        brand: "Levi's",
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    }, ],
};